import { describe, expect, it, vi } from 'vitest';
import { SupabaseAssetTransport } from '../../../src/sync/transport/SupabaseAssetTransport';

const CONFIG={url:'https://example.supabase.co',anonKey:'anon'} as const;

describe('Phase 6D private Asset transport',()=>{
  it('creates staging, uploads to the private bucket and finalizes with the authenticated token',async()=>{const calls:Array<{url:string;init?:RequestInit}>=[];const fetchImpl=vi.fn(async(url:string,init?:RequestInit)=>{calls.push({url,init});if(url.includes('tuck_create_asset_staging'))return new Response(JSON.stringify({kind:'staging',assetId:'asset-1',storagePath:'user/asset-1/original.png',version:1}),{status:200});if(url.includes('/storage/v1/object/'))return new Response(null,{status:200});return new Response(JSON.stringify({kind:'ready',asset:{entityType:'asset',entity:{id:'asset-1',mimeType:'image/png',byteSize:4,remoteState:'ready',version:2}},changeSequence:1}),{status:200});});const transport=new SupabaseAssetTransport(CONFIG,()=> 'user-token',fetchImpl as unknown as typeof fetch);const staging=await transport.createStaging('asset-1','image/png',4);expect(staging.kind).toBe('staging');if(staging.kind==='staging'){await transport.upload(staging.storagePath,'image/png',new Uint8Array([1,2,3,4]));}await transport.finalize('asset-1','device-1');expect(calls.some(x=>x.url.includes('/storage/v1/object/tuck-assets/user/asset-1/original.png'))).toBe(true);for(const call of calls)expect(new Headers(call.init?.headers).get('Authorization')).toBe('Bearer user-token');});
  it('downloads private bytes and never creates a public URL',async()=>{const fetchImpl=vi.fn(async()=>new Response(new Uint8Array([1,2,3]),{status:200,headers:{'content-type':'image/png'}}));const transport=new SupabaseAssetTransport(CONFIG,()=> 'token',fetchImpl as unknown as typeof fetch);const result=await transport.download('u/a/original.png');expect([...result.bytes]).toEqual([1,2,3]);expect(fetchImpl.mock.calls[0][0]).toContain('/storage/v1/object/tuck-assets/');});
});
