import { describe, expect, it, vi } from 'vitest';
import { SupabaseAssetTransport } from '../../../src/sync/transport/SupabaseAssetTransport';

const CONFIG={url:'https://example.supabase.co',anonKey:'anon'} as const;

describe('Phase 6D private Asset transport',()=>{
  it('creates staging, uploads to the private bucket and finalizes with publishable key plus authenticated token',async()=>{const calls:Array<{url:string;init?:RequestInit}>=[];const fetchImpl=vi.fn(async(url:string,init?:RequestInit)=>{calls.push({url,init});if(url.includes('tuck_create_asset_staging'))return new Response(JSON.stringify({kind:'staging',assetId:'asset-1',storagePath:'user/asset-1/original.png',version:1}),{status:200});if(url.includes('/storage/v1/object/'))return new Response(null,{status:200});return new Response(JSON.stringify({kind:'ready',asset:{entityType:'asset',entity:{id:'asset-1',mimeType:'image/png',byteSize:4,remoteState:'ready',version:2}},changeSequence:1}),{status:200});});const transport=new SupabaseAssetTransport(CONFIG,()=> 'user-token',fetchImpl as unknown as typeof fetch);const staging=await transport.createStaging('asset-1','image/png',4);expect(staging.kind).toBe('staging');if(staging.kind==='staging'){await transport.upload(staging.storagePath,'image/png',new Uint8Array([1,2,3,4]));}await transport.finalize('asset-1','device-1');expect(calls.some(x=>x.url.includes('/storage/v1/object/tuck-assets/user/asset-1/original.png'))).toBe(true);for(const call of calls){const headers=new Headers(call.init?.headers);expect(headers.get('apikey')).toBe(CONFIG.anonKey);expect(headers.get('Authorization')).toBe('Bearer user-token');}});
  it('uses the browser-safe default fetch wrapper',async()=>{const fetchImpl=vi.fn<typeof fetch>(async function(this:unknown,_input,_init){expect(this).toBe(globalThis);return new Response(new Uint8Array([1]),{status:200});});vi.stubGlobal('fetch',fetchImpl);try{const transport=new SupabaseAssetTransport(CONFIG,()=> 'token');await transport.download('u/a/original.png');expect(fetchImpl).toHaveBeenCalledOnce();}finally{vi.unstubAllGlobals();}});
  it('downloads private bytes with publishable key plus user JWT and never creates a public URL',async()=>{const fetchImpl=vi.fn<typeof fetch>(async (_input,_init)=>new Response(new Uint8Array([1,2,3]),{status:200,headers:{'content-type':'image/png'}}));const transport=new SupabaseAssetTransport(CONFIG,()=> 'token',fetchImpl as unknown as typeof fetch);const result=await transport.download('u/a/original.png');expect([...result.bytes]).toEqual([1,2,3]);expect(fetchImpl.mock.calls[0][0]).toContain('/storage/v1/object/tuck-assets/');const headers=new Headers(fetchImpl.mock.calls[0][1]?.headers);expect(headers.get('apikey')).toBe(CONFIG.anonKey);expect(headers.get('Authorization')).toBe('Bearer token');});
});
